// ==========================================
// [1] 아이템 데이터 (기존 유지)
// ==========================================
const itemDatabase = {
  // === [유물: Artifacts] ===
  hunter: { name: "사냥꾼의 유물", img: "hunter.png", category: "artifact" },
  clever: { name: "현명함의 유물", img: "clever.png", category: "artifact" },
  pack: { name: "무리의 유물", img: "pack.png", category: "artifact" },
  massive: { name: "거대함의 유물", img: "massive.png", category: "artifact" },
  devious: { name: "기만의 유물", img: "devious.png", category: "artifact" },
  skylord: {
    name: "하늘군주의 유물",
    img: "skylord.png",
    category: "artifact",
  },
  devourer: { name: "탐닉의 유물", img: "devourer.png", category: "artifact" },
  immune: { name: "면역의 유물", img: "immune.png", category: "artifact" },
  strong: { name: "강함의 유물", img: "strong.png", category: "artifact" },
  cunning: { name: "교활함의 유물", img: "cunning.png", category: "artifact" },
  brute: { name: "짐승의 유물", img: "brute.png", category: "artifact" },
  crag: { name: "바위의 유물", img: "crag.png", category: "artifact" },
  destroyer: {
    name: "파괴자의 유물",
    img: "destroyer.png",
    category: "artifact",
  },
  gatekeeper: {
    name: "문지기의 유물",
    img: "gatekeeper.png",
    category: "artifact",
  },
  depths: { name: "깊이의 유물", img: "depths.png", category: "artifact" },
  shadows: { name: "그림자의 유물", img: "shadows.png", category: "artifact" },
  stalker: { name: "추적자의 유물", img: "stalker.png", category: "artifact" },
  chaos: { name: "혼돈의 유물", img: "chaos.png", category: "artifact" },
  void: { name: "공허의 유물", img: "void.png", category: "artifact" },
  growth: { name: "성장의 유물", img: "growth.png", category: "artifact" },
  lost: { name: "헤메임의 유물", img: "lost.png", category: "artifact" },

  // === [공물: Tributes] ===
  claw: { name: "아르젠 발톱", img: "claw.png", category: "tribute" },
  sarco: { name: "사르코 가죽", img: "sarco.png", category: "tribute" },
  venom: { name: "티타노보아 독", img: "venom.png", category: "tribute" },
  sauro: { name: "용각류 척추", img: "sauro.png", category: "tribute" },
  rex: { name: "티라노 팔", img: "rex.png", category: "tribute" },
  mega: { name: "메갈로돈 이빨", img: "mega.png", category: "tribute" },
  allo: { name: "알로 뇌", img: "allo.png", category: "tribute" },
  spino_sail: {
    name: "스피노 지느러미",
    img: "spino_sail.png",
    category: "tribute",
  },
  giga: { name: "기가노토 심장", img: "giga.png", category: "tribute" },
  tuso: { name: "투소 촉수", img: "tuso.png", category: "tribute" },
  basilo: { name: "바실로 지방", img: "basilo.png", category: "tribute" },
  yuty: { name: "유티 폐", img: "yuty.png", category: "tribute" },
  talon_fire: {
    name: "화염와이번 발톱",
    img: "talon_fire.png",
    category: "tribute",
  },
  talon_lightning: {
    name: "번개와이번 발톱",
    img: "talon_lightning.png",
    category: "tribute",
  },
  talon_poison: {
    name: "맹독와이번 발톱",
    img: "talon_poison.png",
    category: "tribute",
  },
  nameless: { name: "네임리스 독", img: "nameless.png", category: "tribute" },
  feather: {
    name: "락 드레이크 깃털",
    img: "feather.png",
    category: "tribute",
  },
  basilisk_scale: {
    name: "바실리스크 비늘",
    img: "basilisk_scale.png",
    category: "tribute",
  },
  pheromone: { name: "리퍼 페로몬", img: "pheromone.png", category: "tribute" },
  corrupted_heart: {
    name: "오염된 심장",
    img: "corrupted_heart.png",
    category: "tribute",
  },
  mutagen: { name: "뮤타젠", img: "mutagen.png", category: "tribute" },
  thyla_hook: {
    name: "틸라콜레오 갈고리 발톱",
    img: "thyla_hook.png",
    category: "tribute",
  },
  toxin: { name: "메갈라니아 독소", img: "toxin.png", category: "tribute" },
  theri_claw: {
    name: "테리지노 발톱",
    img: "theri_claw.png",
    category: "tribute",
  },
  crystal_talon: {
    name: "크리스탈 와이번 발톱",
    img: "crystal_talon.png",
    category: "tribute",
  },
  primal_crystal: {
    name: "프라이멀 크리스탈",
    img: "primal_crystal.png",
    category: "tribute",
  },

  //알파 재료들
  Alpha_Raptor_Claw: {
    name: "알파 랩터의 발톱",
    img: "Alpha_Raptor_Claw.png",
    category: "alpha",
  },
  Alpha_Carnotaurus_Arm: {
    name: "알파 카르노 팔",
    img: "Alpha_Carnotaurus_Arm.png",
    category: "alpha",
  },
  Alpha_Tyrannosaurus_Tooth: {
    name: "알파 티라노 이빨",
    img: "Alpha_Tyrannosaurus_Tooth.png",
    category: "alpha",
  },
  Alpha_Megalodon_Fin: {
    name: "알파 메갈로돈 지느러미",
    img: "Alpha_Megalodon_Fin.png",
    category: "alpha",
  },
  Alpha_Mosasaur_Tooth: {
    name: "알파 모사 이빨",
    img: "Alpha_Mosasaur_Tooth.png",
    category: "alpha",
  },
  Alpha_Tusoteuthis_Eye: {
    name: "알파 투소 눈",
    img: "Alpha_Tusoteuthis_Eye.png",
    category: "alpha",
  },
  Alpha_Leedsichthys_Blubber: {
    name: "알파 리드시크 지방",
    img: "Alpha_Leedsichthys_Blubber.png",
    category: "alpha",
  },
  Alpha_Basilisk_Fang: {
    name: "알파 바실리크스 독니",
    img: "Alpha_Basilisk_Fang.png",
    category: "alpha",
  },

  Alpha_Karkinos_Claw: {
    name: "알파 카르키노스 집게발",
    img: "Alpha_Karkinos_Claw.png",
    category: "alpha",
  },
  Alpha_Reaper_King_Barb: {
    name: "알파 리퍼 킹 미늘",
    img: "Alpha_Reaper_King_Barb.png",
    category: "alpha",
  },
  alpha_crystal_talon: {
    name: "알파 크리스탈 와이번 발톱",
    img: "alpha_crystal_talon.png",
    category: "alpha",
  },

  // === [기타 및 트로피] ===
  trophy_brood_gamma: {
    name: "브루드마더 트로피 (감마)",
    img: "trophy_brood.png",
    category: "trophy",
  },
  trophy_brood_beta: {
    name: "브루드마더 트로피 (베타)",
    img: "trophy_brood.png",
    category: "trophy",
  },
  trophy_brood_alpha: {
    name: "브루드마더 트로피 (알파)",
    img: "trophy_brood.png",
    category: "trophy",
  },
  trophy_mega_gamma: {
    name: "메가피테쿠스 트로피 (감마)",
    img: "trophy_mega.png",
    category: "trophy",
  },
  trophy_mega_beta: {
    name: "메가피테쿠스 트로피 (베타)",
    img: "trophy_mega.png",
    category: "trophy",
  },
  trophy_mega_alpha: {
    name: "메가피테쿠스 트로피 (알파)",
    img: "trophy_mega.png",
    category: "trophy",
  },
  trophy_dragon_gamma: {
    name: "드래곤 트로피 (감마)",
    img: "trophy_dragon.png",
    category: "trophy",
  },
  trophy_dragon_beta: {
    name: "드래곤 트로피 (베타)",
    img: "trophy_dragon.png",
    category: "trophy",
  },
  trophy_dragon_alpha: {
    name: "드래곤 트로피 (알파)",
    img: "trophy_dragon.png",
    category: "trophy",
  },
  //추가트로피
  Desert_Titan_Trophy: {
    name: "데저트 타이탄 트로피",
    img: "Desert_Titan_Trophy.png",
    category: "trophy",
  },
  Ice_Titan_Trophy: {
    name: "아이스 타이탄 트로피",
    img: "Ice_Titan_Trophy.png",
    category: "trophy",
  },
  Forest_Titan_Trophy: {
    name: "포레스트 타이탄 트로피",
    img: "Forest_Titan_Trophy.png",
    category: "trophy",
  },
  King_Titan_Trophy_gamma: {
    name: "킹 타이탄 트로피 (감마)",
    img: "King_Titan_Trophy.png",
    category: "trophy",
  },
  King_Titan_Trophy_beta: {
    name: "킹 타이탄 트로피 (베타)",
    img: "King_Titan_Trophy.png",
    category: "trophy",
  },
};

// ==========================================================
// [2] 보스 데이터 (Google Sheet '시트2' 내용 100% 반영)
// 정렬 순서: 아일 -> 라그 -> 익팅 -> 센터 -> 스코치드 -> 에버 -> 제네1 -> 제네2 -> 나머지
// ==========================================================
const bossDatabase = [
  // ----------------------------------------------------
  // 1. 아일랜드 (The Island) - Sheet2 Col 1, 2, 3
  // ----------------------------------------------------
  {
    id: "broodmother",
    name: "브루드마더",
    map: "The Island",
    img: "broodmother.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "clever", count: 1 },
          { id: "hunter", count: 1 },
          { id: "massive", count: 1 },
        ],
        element: 20,
        // 파일 원문: Tek Foundation, Tek Replicator, Tek Triangle Ceiling, Tek Triangle Foundation, Tek Triangle Roof, Sloped Tek Roof, Sloped Tek Wall Left, Sloped Tek Wall Right
        unlocks: [
          "테크 토대",
          "테크 복제기",
          "테크 삼각 천장",
          "테크 삼각 토대",
          "테크 삼각 지붕",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "hunter", count: 1 },
          { id: "clever", count: 1 },
          { id: "massive", count: 1 },
          { id: "claw", count: 5 },
          { id: "sarco", count: 5 },
          { id: "venom", count: 5 },
          { id: "sauro", count: 5 },
        ],
        element: 56,
        // 파일 원문: Tek Boots, Tek Catwalk, Tek Ceiling, Tek Fence Foundation, Tek Foundation, Tek Ladder, Tek Pillar, Tek Railing, Tek Ramp, Tek Replicator, Tek Staircase, Tek Triangle Ceiling, Tek Triangle Foundation, Tek Triangle Roof, Tek Wall
        unlocks: [
          "경사진 테크 지붕",
          "경사진 테크 벽 왼쪽",
          "경사진 테크 벽 오른쪽",
          "테크 장화",
          "테크 좁은 통로",
          "테크 천장",
          "테크 울타리 토대",
          "테크 토대",
          "테크 사다리",
          "테크 기둥",
          "테크 난간",
          "테크 경사로",
          "테크 복제기",
          "테크 계단",
          "테크 삼각 천장",
          "테크 삼각 토대",
          "테크 삼각 지붕",
          "테크 벽",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "hunter", count: 1 },
          { id: "clever", count: 1 },
          { id: "massive", count: 1 },
          { id: "claw", count: 10 },
          { id: "sarco", count: 10 },
          { id: "venom", count: 10 },
          { id: "sauro", count: 10 },
        ],
        element: 148,
        // 파일 원문: Mosasaur Tek Saddle, Sloped Tek Roof... (이하 감마/베타 포함 전체)
        unlocks: [
          "모사사우루스 테크 안장",
          "경사진 테크 지붕",
          "경사진 테크 벽 왼쪽",
          "경사진 테크 벽 오른쪽",
          "테크 장화",
          "테크 좁은 통로",
          "테크 천장",
          "테크 울타리 토대",
          "테크 토대",
          "테크 헬멧",
          "테크 사다리",
          "테크 기둥",
          "테크 난간",
          "테크 경사로",
          "테크 복제기",
          "테크 계단",
          "테크 삼각 천장",
          "테크 삼각 토대",
          "테크 삼각 지붕",
          "테크 터렛",
          "테크 벽",
        ],
      },
    },
  },
  {
    id: "megapithecus",
    name: "메가피테쿠스",
    map: "The Island",
    img: "megapithecus.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "pack", count: 1 },
          { id: "devourer", count: 1 },
          { id: "brute", count: 1 },
        ],
        element: 40,
        // 파일 원문: Tek Gauntlets, Tek Hatchframe, Tek Replicator, Tek Trapdoor, Tek Window, Tek Windowframe
        unlocks: [
          "테크 건틀릿",
          "테크 해치 프레임",
          "테크 복제기",
          "테크 트랩도어",
          "테크 창문",
          "테크 창틀",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "pack", count: 1 },
          { id: "devourer", count: 1 },
          { id: "brute", count: 1 },
          { id: "rex", count: 5 },
          { id: "mega", count: 5 },
          { id: "allo", count: 5 },
          { id: "spino_sail", count: 5 },
        ],
        element: 110,
        // 파일 원문: Tek Dinosaur Gate, Tek Dinosaur Gateway, Tek Door, Tek Doorframe, Tek Gauntlets, Tek Generator, Tek Hatchframe, Tek Replicator, Tek Rifle, Tek Trapdoor, Tek Trough, Tek Window, Tek Windowframe
        unlocks: [
          "테크 공룡 문",
          "테크 공룡 문틀",
          "테크 문",
          "테크 문틀",
          "테크 건틀릿",
          "테크 발전기",
          "테크 해치 프레임",
          "테크 복제기",
          "테크 소총",
          "테크 트랩도어",
          "테크 먹이통",
          "테크 창문",
          "테크 창틀",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "pack", count: 1 },
          { id: "devourer", count: 1 },
          { id: "brute", count: 1 },
          { id: "rex", count: 10 },
          { id: "mega", count: 10 },
          { id: "allo", count: 10 },
          { id: "spino_sail", count: 10 },
        ],
        element: 220,
        // 파일 원문: Large Tek Wall, Rex Tek Saddle, Tek Dinosaur Gate... (누적)
        unlocks: [
          "대형 테크 벽",
          "렉스 테크 안장",
          "테크 공룡 문",
          "테크 공룡 문틀",
          "테크 문",
          "테크 문틀",
          "테크 건틀릿",
          "테크 발전기",
          "테크 수류탄",
          "테크 해치 프레임",
          "테크 복제기",
          "테크 소총",
          "테크 트랩도어",
          "테크 먹이통",
          "테크 창문",
          "테크 창틀",
        ],
      },
    },
  },
  {
    id: "dragon",
    name: "드래곤",
    map: "The Island",
    img: "dragon.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "skylord", count: 1 },
          { id: "immune", count: 1 },
          { id: "strong", count: 1 },
          { id: "cunning", count: 1 },
        ],
        element: 80,
        // 파일 원문: Behemoth Tek Gate, Behemoth Tek Gateway, Megalodon Tek Saddle, Tapejara Tek Saddle, Tek Leggings, Tek Replicator
        unlocks: [
          "베헤모스 테크 문",
          "베헤모스 테크 문틀",
          "메갈로돈 테크 안장",
          "타페하라 테크 안장",
          "테크 레깅스",
          "테크 복제기",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "skylord", count: 1 },
          { id: "immune", count: 1 },
          { id: "strong", count: 1 },
          { id: "cunning", count: 1 },
          { id: "giga", count: 1 },
          { id: "tuso", count: 5 },
          { id: "basilo", count: 5 },
          { id: "yuty", count: 5 },
          { id: "rex", count: 5 },
          { id: "allo", count: 5 },
        ],
        element: 220,
        // 파일 원문: Behemoth Tek Gate... Tek Dedicated Storage... Vacuum Compartment
        unlocks: [
          "베헤모스 테크 문",
          "베헤모스 테크 문틀",
          "메갈로돈 테크 안장",
          "타페하라 테크 안장",
          "테크 전용 보관함",
          "테크 이중 문",
          "테크 이중 문틀",
          "테크 울타리 지지대",
          "테크 역장",
          "테크 레깅스",
          "테크 복제기",
          "테크 계단",
          "테크 송신기",
          "테크 진공관",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "skylord", count: 1 },
          { id: "immune", count: 1 },
          { id: "strong", count: 1 },
          { id: "cunning", count: 1 },
          { id: "giga", count: 2 },
          { id: "tuso", count: 10 },
          { id: "basilo", count: 10 },
          { id: "yuty", count: 10 },
          { id: "rex", count: 15 },
          { id: "allo", count: 10 },
        ],
        element: 440,
        // 파일 원문: ... Cloning Chamber ... Vacuum Compartment Moonpool
        unlocks: [
          "베헤모스 테크 문",
          "베헤모스 테크 문틀",
          "복제실",
          "메갈로돈 테크 안장",
          "타페하라 테크 안장",
          "테크 가슴보호구",
          "테크 전용 보관함",
          "테크 이중 문",
          "테크 이중 문틀",
          "테크 울타리 지지대",
          "테크 역장",
          "테크 레깅스",
          "테크 복제기",
          "테크 계단",
          "테크 텔레포터",
          "테크 송신기",
          "테크 진공관",
          "테크 진공관 문틀",
        ],
      },
    },
  },
  // ▼ 이 코드를 bossDatabase 배열 안에 복사해서 넣으세요.
  {
    id: "overseer", // 영어 ID (겹치지 않게)
    name: "감독관", // 화면에 보일 이름
    map: "The Island", // 맵 이름
    img: "Dossier_Overseer.png", // 이미지 파일명 (images 폴더에 있어야 함)
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "trophy_brood_gamma", count: 1 },
          { id: "trophy_mega_gamma", count: 1 },
          { id: "trophy_dragon_gamma", count: 1 },
        ], // 필요 재료
        unlocks: ["Gamma Ascension Implant"], // 해금 목록
      },
      beta: {
        level: "Beta",
        req: [
          { id: "trophy_brood_beta", count: 1 },
          { id: "trophy_mega_beta", count: 1 },
          { id: "trophy_dragon_beta", count: 1 },
          { id: "Alpha_Raptor_Claw", count: 1 },
          { id: "Alpha_Carnotaurus_Arm", count: 1 },
          { id: "Alpha_Tyrannosaurus_Tooth", count: 1 },
        ],
        unlocks: ["Beta Ascension Implant"],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "trophy_brood_alpha", count: 1 },
          { id: "trophy_mega_alpha", count: 1 },
          { id: "trophy_dragon_alpha", count: 1 },
          { id: "Alpha_Raptor_Claw", count: 1 },
          { id: "Alpha_Carnotaurus_Arm", count: 1 },
          { id: "Alpha_Tyrannosaurus_Tooth", count: 1 },
          { id: "Alpha_Megalodon_Fin", count: 1 },
          { id: "Alpha_Mosasaur_Tooth", count: 1 },
          { id: "Alpha_Tusoteuthis_Eye", count: 1 },
          { id: "Alpha_Leedsichthys_Blubber", count: 1 },
        ],
        unlocks: ["Alpha Ascension Implant", "Tek ATV"],
      },
    },
  }, // <-- 다음 보스가 있다면 콤마 필수!

  // ----------------------------------------------------
  // 2. 라그나로크 (Ragnarok) - Sheet2 Col 13, 14, 15
  // [중요] 파일에 있는 그대로 '아일랜드/스코치드' 아이템이 포함된 목록입니다.
  // ----------------------------------------------------
  {
    id: "ragnarok",
    name: "라그나로크",
    map: "Ragnarok",
    img: "ragnarok_boss.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "clever", count: 1 },
          { id: "cunning", count: 1 },
          { id: "devious", count: 1 },
          { id: "devourer", count: 1 },
          { id: "hunter", count: 1 },
          { id: "immune", count: 1 },
          { id: "massive", count: 1 },
          { id: "pack", count: 1 },
          { id: "skylord", count: 1 },
          { id: "strong", count: 1 },
        ],
        element: 65,
        // 파일 원문: Behemoth Tek Gate, Behemoth Tek Gateway, Megalodon Tek Saddle, Tapejara Tek Saddle, Tek Gauntlets, Tek Generator, Tek Leggings, Tek Light, Tek Replicator, Tek Trough
        unlocks: [
          "베헤모스 테크 문",
          "베헤모스 테크 문틀",
          "메갈로돈 테크 안장",
          "타페하라 테크 안장",
          "테크 건틀릿",
          "테크 발전기",
          "테크 레깅스",
          "테크 조명",
          "테크 복제기",
          "테크 먹이통",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "clever", count: 1 },
          { id: "cunning", count: 1 },
          { id: "devious", count: 1 },
          { id: "devourer", count: 1 },
          { id: "hunter", count: 1 },
          { id: "immune", count: 1 },
          { id: "massive", count: 1 },
          { id: "pack", count: 1 },
          { id: "skylord", count: 1 },
          { id: "strong", count: 1 },
          { id: "claw", count: 10 },
          { id: "basilo", count: 10 },
          { id: "toxin", count: 10 },
          { id: "mega", count: 10 },
          { id: "sarco", count: 10 },
          { id: "sauro", count: 10 },
          { id: "spino_sail", count: 10 },
          { id: "thyla_hook", count: 10 },
          { id: "venom", count: 10 },
          { id: "tuso", count: 10 },
        ],
        element: 200,
        // 파일 원문: ... Tek Forcefield ... Tek Transmitter ... Vacuum Compartment (전용 보관함 없음)
        unlocks: [
          "베헤모스 테크 문",
          "베헤모스 테크 문틀",
          "메갈로돈 테크 안장",
          "타페하라 테크 안장",
          "테크 역장",
          "테크 건틀릿",
          "테크 발전기",
          "테크 레깅스",
          "테크 조명",
          "테크 복제기",
          "테크 소총",
          "테크 검",
          "테크 송신기",
          "테크 먹이통",
          "테크 진공관",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "clever", count: 1 },
          { id: "cunning", count: 1 },
          { id: "devious", count: 1 },
          { id: "devourer", count: 1 },
          { id: "hunter", count: 1 },
          { id: "immune", count: 1 },
          { id: "massive", count: 1 },
          { id: "pack", count: 1 },
          { id: "skylord", count: 1 },
          { id: "strong", count: 1 },
          { id: "claw", count: 25 },
          { id: "basilo", count: 25 },
          { id: "toxin", count: 25 },
          { id: "mega", count: 25 },
          { id: "sarco", count: 25 },
          { id: "sauro", count: 25 },
          { id: "spino_sail", count: 25 },
          { id: "thyla_hook", count: 25 },
          { id: "venom", count: 25 },
          { id: "tuso", count: 25 },
        ],
        element: 410,
        // 파일 원문: ... Cloning Chamber ... Tek Dedicated Storage ... Moonpool
        unlocks: [
          "베헤모스 테크 문",
          "베헤모스 테크 문틀",
          "복제실",
          "메갈로돈 테크 안장",
          "렉스 테크 안장",
          "타페하라 테크 안장",
          "테크 가슴보호구",
          "테크 역장",
          "테크 건틀릿",
          "테크 발전기",
          "테크 수류탄",
          "테크 레깅스",
          "테크 조명",
          "테크 복제기",
          "테크 소총",
          "테크 방패",
          "테크 검",
          "테크 텔레포터",
          "테크 송신기",
          "테크 먹이통",
          "테크 진공관",
          "테크 진공관 문틀",
        ],
      },
    },
  },

  // ----------------------------------------------------
  // 3. 익스팅션 (Extinction) - Sheet2 Col 22, 23, 24 (Titans)
  // * 킹 타이탄은 파일 마지막에 트로피만 있어서 기존 유지 또는 타이탄들만 추가
  // ----------------------------------------------------
  {
    id: "Desert_Titan",
    name: "데저트 타이탄",
    map: "Extinction",
    img: "desert_titan.png",
    difficulties: {
      alpha: {
        level: "Alpha",
        req: [
          { id: "chaos", count: 1 },
          { id: "corrupted_heart", count: 100 },
          { id: "talon_fire", count: 10 },
          { id: "sarco", count: 10 },
        ],
        element: 0,
        unlocks: [
          "테크 장화",
          "테크 전용 보관함",
          "테크 발전기",
          "테크 레일건",
          "테크 복제기",
          "테크 먹이통",
        ],
      },
    },
  },

  {
    id: "Forest_Titan_Trophy",
    name: "포레스트 타이탄",
    map: "Extinction",
    img: "forest_titan.png",
    difficulties: {
      alpha: {
        level: "Alpha",
        req: [
          { id: "growth", count: 1 },
          { id: "corrupted_heart", count: 100 },
          { id: "sauro", count: 10 },
          { id: "rex", count: 10 },
        ],
        element: 0,
        unlocks: [
          "렉스 테크 안장",
          "테크 건틀릿",
          "테크 레깅스",
          "테크 복제기",
          "테크 검",
          "테크 텔레포터"
        ],
      },
    },
  },

  {
    id: "Ice_Titan_Trophy",
    name: "아이스 타이탄",
    map: "Extinction",
    img: "ice_titan.png",
    difficulties: {
      alpha: {
        level: "Alpha",
        req: [
          { id: "void", count: 1 },
          { id: "corrupted_heart", count: 100 },
          { id: "spino_sail", count: 10 },
          { id: "theri_claw", count: 10 },
        ],
        element: 0,
        unlocks: [
          "타페하라 테크 안장",
          "테크 가슴보호구",
          "테크 역장",
          "테크 헬멧",
          "테크 복제기",
          "테크 소총"
        ],
      },
    },
  },

  {
    id: "kingtitan",
    name: "킹 타이탄",
    map: "Extinction",
    img: "kingtitan.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "Desert_Titan_Trophy", count: 1 },
          { id: "Ice_Titan_Trophy", count: 1 },
          { id: "Forest_Titan_Trophy", count: 1 },
          { id: "Alpha_Tyrannosaurus_Tooth", count: 5 },
          { id: "corrupted_heart", count: 150 },
          { id: "venom", count: 10 },
        ],
        element: 0,
        unlocks: [
          "메카 모듈: M.O.M.I.",
          "호모 데우스 기록",
          "킹 타이탄 트로피 (감마)",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "Desert_Titan_Trophy", count: 1 },
          { id: "Ice_Titan_Trophy", count: 1 },
          { id: "Forest_Titan_Trophy", count: 1 },
          { id: "King_Titan_Trophy_gamma", count: 1 },
          { id: "Alpha_Tyrannosaurus_Tooth", count: 10 },
          { id: "corrupted_heart", count: 300 },
          { id: "venom", count: 20 },
        ],
        element: 0,
        unlocks: ["킹 타이탄 트로피 (베타)"],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "Desert_Titan_Trophy", count: 1 },
          { id: "Ice_Titan_Trophy", count: 1 },
          { id: "Forest_Titan_Trophy", count: 1 },
          { id: "King_Titan_Trophy_beta", count: 1 },
          { id: "Alpha_Tyrannosaurus_Tooth", count: 10 },
          { id: "corrupted_heart", count: 300 },
          { id: "giga", count: 20 },
          { id: "spino_sail", count: 20 },
          { id: "venom", count: 20 },
        ],
        element: 0,
        unlocks: ["킹 타이탄 트로피 (알파)", "호모 데우스 스킨"],
      },
    },
  },

  

  // ----------------------------------------------------
  // 4. 더 센터 (The Center) - Sheet2 Col 10, 11, 12
  // ----------------------------------------------------
  {
    id: "thecenter",
    name: "더 센터",
    map: "The Center",
    img: "the_center.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "brute", count: 1 },
          { id: "clever", count: 1 },
          { id: "cunning", count: 1 },
          { id: "devious", count: 1 },
          { id: "devourer", count: 1 },
          { id: "hunter", count: 1 },
          { id: "immune", count: 1 },
          { id: "massive", count: 1 },
          { id: "pack", count: 1 },
          { id: "skylord", count: 1 },
          { id: "strong", count: 1 },
        ],
        element: 60,
        // 파일 원문: Tek Foundation, Tek Gauntlets, Tek Hatchframe, Tek Replicator, Tek Trapdoor, Tek Window, Tek Windowframe
        unlocks: [
          "테크 토대",
          "테크 건틀릿",
          "테크 해치프레임",
          "테크 복제기",
          "테크 트랩도어",
          "테크 창문",
          "테크 창문틀",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "brute", count: 1 },
          { id: "clever", count: 1 },
          { id: "cunning", count: 1 },
          { id: "devious", count: 1 },
          { id: "devourer", count: 1 },
          { id: "hunter", count: 1 },
          { id: "immune", count: 1 },
          { id: "massive", count: 1 },
          { id: "pack", count: 1 },
          { id: "skylord", count: 1 },
          { id: "strong", count: 1 },
          { id: "claw", count: 10 },
          { id: "basilo", count: 10 },
          { id: "toxin", count: 10 },
          { id: "mega", count: 10 },
          { id: "sarco", count: 10 },
          { id: "sauro", count: 10 },
          { id: "spino_sail", count: 10 },
          { id: "thyla_hook", count: 10 },
          { id: "venom", count: 10 },
          { id: "tuso", count: 10 },
        ],
        element: 166,
        // 파일 원문: Sloped Tek Roof... Tek Rifle... (이하 누적)
        unlocks: [
          "경사진 테크 지붕",
          "경사진 테크 벽(좌)",
          "경사진 테크 벽(우)",
          "테크 부츠",
          "테크 캣워크",
          "테크 천장",
          "테크 공룡 문",
          "테크 공룡 게이트",
          "테크 문",
          "테크 문틀",
          "테크 울타리 토대",
          "테크 토대",
          "테크 건틀릿",
          "테크 발전기",
          "테크 해치프레임",
          "테크 사다리",
          "테크 기둥",
          "테크 난간",
          "테크 경사로",
          "테크 복제기",
          "테크 소총",
          "테크 계단",
          "테크 트랩도어",
          "테크 먹이통",
          "테크 벽",
          "테크 창문",
          "테크 창문틀",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "brute", count: 1 },
          { id: "clever", count: 1 },
          { id: "cunning", count: 1 },
          { id: "devious", count: 1 },
          { id: "devourer", count: 1 },
          { id: "hunter", count: 1 },
          { id: "immune", count: 1 },
          { id: "massive", count: 1 },
          { id: "pack", count: 1 },
          { id: "skylord", count: 1 },
          { id: "strong", count: 1 },
          { id: "claw", count: 25 },
          { id: "basilo", count: 25 },
          { id: "toxin", count: 25 },
          { id: "mega", count: 25 },
          { id: "sarco", count: 25 },
          { id: "sauro", count: 25 },
          { id: "spino_sail", count: 25 },
          { id: "thyla_hook", count: 25 },
          { id: "venom", count: 25 },
          { id: "tuso", count: 25 },
        ],
        element: 368,
        // 파일 원문: Mosasaur Tek Saddle, Rex Tek Saddle... (이하 누적)
        unlocks: [
          "모사사우루스 테크 안장",
          "테크 렉스 안장",
          "경사진 테크 지붕",
          "경사진 테크 벽(좌)",
          "경사진 테크 벽(우)",
          "테크 부츠",
          "테크 캣워크",
          "테크 천장",
          "테크 공룡 문",
          "테크 공룡 게이트",
          "테크 문",
          "테크 문틀",
          "테크 울타리 토대",
          "테크 토대",
          "테크 건틀릿",
          "테크 발전기",
          "테크 수류탄",
          "테크 해치프레임",
          "테크 헬멧",
          "테크 사다리",
          "테크 기둥",
          "테크 난간",
          "테크 경사로",
          "테크 복제기",
          "테크 소총",
          "테크 계단",
          "테크 트랩도어",
          "테크 먹이통",
          "테크 터렛",
          "테크 벽",
          "테크 창문",
          "테크 창문틀",
        ],
      },
    },
  },

  // ----------------------------------------------------
  // 5. 스코치드 어스 (Scorched Earth) - Sheet2 Col 16, 17, 18
  // ----------------------------------------------------
  {
    id: "manticore",
    name: "만티코어",
    map: "Scorched Earth",
    img: "manticore.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "gatekeeper", count: 1 },
          { id: "crag", count: 1 },
          { id: "destroyer", count: 1 },
          { id: "talon_fire", count: 2 },
          { id: "talon_lightning", count: 2 },
          { id: "talon_poison", count: 2 },
        ],
        element: 38,
        // 파일 원문: Tek Gauntlets, Tek Generator, Tek Leggings, Tek Replicator, Tek Trough
        unlocks: [
          "테크 건틀릿",
          "테크 발전기",
          "테크 레깅스",
          "테크 복제기",
          "테크 먹이통"
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "gatekeeper", count: 1 },
          { id: "crag", count: 1 },
          { id: "destroyer", count: 1 },
          { id: "talon_fire", count: 10 },
          { id: "talon_lightning", count: 10 },
          { id: "talon_poison", count: 10 },
        ],
        element: 135,
        // 파일 원문: Tapejara Tek Saddle, Tek Dedicated Storage, Tek Gauntlets, Tek Generator, Tek Leggings, Tek Replicator, Tek Rifle, Tek Shield, Tek Trough
        unlocks: [
          "타페야라 테크 안장",
          "테크 전용 보관함",
          "테크 건틀릿",
          "테크 발전기",
          "테크 레깅스",
          "테크 복제기",
          "테크 소총",
          "테크 방패",
          "테크 먹이통",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "gatekeeper", count: 1 },
          { id: "crag", count: 1 },
          { id: "destroyer", count: 1 },
          { id: "talon_fire", count: 20 },
          { id: "talon_lightning", count: 20 },
          { id: "talon_poison", count: 20 },
        ],
        element: 285,
        // 파일 원문: Cloning Chamber, Rex Tek Saddle, Tapejara Tek Saddle... (이하 누적)
        unlocks: [
          "클로닝 챔버",
          "테크 렉스 안장",
          "타페야라 테크 안장",
          "테크 전용 보관함",
          "테크 포스필드",
          "테크 건틀릿",
          "테크 발전기",
          "테크 수류탄",
          "테크 레깅스",
          "테크 복제기",
          "테크 소총",
          "테크 방패",
          "테크 텔레포터",
          "테크 먹이통",
        ],
      },
    },
  },

  // ----------------------------------------------------
  // 6. 에버레이션 (Aberration) - Sheet2 Col 19, 20, 21
  // ----------------------------------------------------
  {
    id: "rockwell",
    name: "로크웰",
    map: "Aberration",
    img: "rockwell.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "depths", count: 1 },
          { id: "shadows", count: 1 },
          { id: "stalker", count: 1 },
        ],
        element: 0,
        // 파일 원문: Gamma Aberrant Implant, Tek Gauntlets, Tek Generator, Tek Leggings, Tek Replicator, Tek Sleeping Pod, Tek Trough
        unlocks: [
          "감마 에버레이션 임플란트",
          "테크 건틀릿",
          "테크 발전기",
          "테크 레깅스",
          "테크 복제기",
          "테크 침대",
          "테크 먹이통"
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "depths", count: 1 },
          { id: "shadows", count: 1 },
          { id: "stalker", count: 1 },
          { id: "basilisk_scale", count: 4 },
          { id: "nameless", count: 12 },
          { id: "pheromone", count: 2 },
          { id: "feather", count: 2 },
        ],
        element: 0,
        // 파일 원문: Beta Aberrant Implant, Rock Drake Tek Saddle, Tek Boots... (이하 누적)
        unlocks: [
          "베타 에버레이션 임플란트",
          "락 드레이크 테크 안장",
          "테크 장화",
          "테크 가슴보호구",
          "테크 전용 보관함",
          "테크 건틀릿",
          "테크 발전기",
          "테크 헬멧",
          "테크 레깅스",
          "테크 복제기",
          "테크 소총",
          "테크 침대",
          "테크 먹이통"
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "depths", count: 1 },
          { id: "shadows", count: 1 },
          { id: "stalker", count: 1 },
          { id: "basilisk_scale", count: 8 },
          { id: "nameless", count: 20 },
          { id: "pheromone", count: 7 },
          { id: "feather", count: 7 },
          { id: "Alpha_Basilisk_Fang", count: 1 },
          { id: "Alpha_Karkinos_Claw", count: 1 },
          { id: "Alpha_Reaper_King_Barb", count: 1 },
        ],
        element: 0,
        // 파일 원문: Alpha Aberrant Implant, Cloning Chamber, Rex Tek Saddle... (이하 누적)
        unlocks: [
          "알파 에버레이션 임플란트",
          "복제실",
          "렉스 테크 안장",
          "락 드레이크 테크 안장",
          "테크 장화",
          "테크 가슴보호구",
          "테크 전용 보관함",
          "테크 역장",
          "테크 건틀릿",
          "테크 발전기",
          "테크 헬멧",
          "테크 레깅스",
          "테크 레일건",
          "테크 복제기",
          "테크 소총",
          "테크 침대",
          "테크 텔레포터",
          "테크 먹이통"
        ],
      },
    },
  },

  // ----------------------------------------------------
  // 7. 제네시스 파트 1 (Genesis Part 1)
  // ----------------------------------------------------
  {
    id: "mastercontroller",
    name: "마스터 컨트롤러",
    map: "Genesis Part 1",
    img: "master_controller.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [],
        element: 40,
        unlocks: [
          "테크 호버 스키프",
          "테크 복제기",
          "테크 센서",
          "테크 건틀릿",
          "테크 레깅스",
          "테크 부츠",
        ],
      },
      beta: {
        level: "Beta",
        req: [],
        element: 110,
        unlocks: [
          "테크 숄더 캐논",
          "순항 미사일",
          "테크 헬멧",
          "테크 소총",
          "테크 흉갑",
          "테크 검",
          "테크 방패",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [],
        element: 220,
        unlocks: [
          "테크 유탄 발사기",
          "테크 레일건",
          "테크 렉스 안장",
          "아스트로세터스 테크 안장",
          "마스터 컨트롤러 트로피",
        ],
      },
    },
  },

  // ----------------------------------------------------
  // 8. 제네시스 파트 2 (Genesis Part 2)
  // ----------------------------------------------------
  {
    id: "rockwellprime",
    name: "로크웰 프라임",
    map: "Genesis Part 2",
    img: "rockwell_prime.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [{ id: "mutagen", count: 6 }],
        element: 0,
        unlocks: [
          "엑소 멕",
          "테크 복제기",
          "알 보큐베이터",
          "테크 작물 밭",
          "호버 세일",
          "테크 수통",
          "테크 캔틴",
          "테크 건틀릿",
          "테크 레깅스",
          "테크 부츠",
        ],
      },
      beta: {
        level: "Beta",
        req: [{ id: "mutagen", count: 12 }],
        element: 0,
        unlocks: [
          "테크 전용 보관함",
          "테크 스트라이더 안장",
          "테크 권총",
          "테크 활",
          "테크 헬멧",
          "테크 흉갑",
          "테크 소총",
          "테크 검",
          "테크 호버 스키프",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [{ id: "mutagen", count: 24 }],
        element: 0,
        unlocks: ["연방 엑소 슈트", "로크웰 프라임 트로피"],
      },
    },
  },

  // ----------------------------------------------------
  // 9. 나머지 (Others)
  // ----------------------------------------------------
  {
    id: "valguero",
    name: "발게로 (3종 보스)",
    map: "Valguero",
    img: "manticore.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "devourer", count: 1 },
          { id: "pack", count: 1 },
          { id: "skylord", count: 1 },
          { id: "allo", count: 5 },
          { id: "claw", count: 5 },
          { id: "sarco", count: 5 },
          { id: "sauro", count: 5 },
          { id: "venom", count: 5 },
        ],
        element: 90,
        unlocks: [
          "테크 복제기",
          "테크 건틀릿",
          "테크 레깅스",
          "테크 발전기",
          "테크 먹이통",
          "테크 창문/문/벽/천장 세트",
          "테크 해치프레임",
          "테크 트랩도어",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "cunning", count: 1 },
          { id: "immune", count: 1 },
          { id: "strong", count: 1 },
          { id: "allo", count: 10 },
          { id: "claw", count: 8 },
          { id: "sarco", count: 8 },
          { id: "sauro", count: 8 },
          { id: "venom", count: 5 },
          { id: "rex", count: 10 },
        ],
        element: 255,
        unlocks: [
          "테크 전용 보관함",
          "테크 공룡 게이트",
          "테크 공룡 문",
          "테크 문",
          "테크 문틀",
          "테크 포스필드",
          "테크 소총",
          "테크 송신기",
          "진공 구획",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "brute", count: 1 },
          { id: "crag", count: 1 },
          { id: "destroyer", count: 1 },
          { id: "gatekeeper", count: 1 },
          { id: "allo", count: 15 },
          { id: "claw", count: 15 },
          { id: "sarco", count: 10 },
          { id: "venom", count: 10 },
          { id: "rex", count: 15 },
          { id: "giga", count: 2 },
        ],
        element: 520,
        unlocks: [
          "클로닝 챔버",
          "테크 렉스 안장",
          "테크 흉갑",
          "테크 수류탄",
          "테크 헬멧",
          "테크 텔레포터",
          "진공 구획 문",
          "발게로 3종 트로피",
        ],
      },
    },
  },
  {
    id: "crystalwyvern",
    name: "크리스탈 와이번 퀸",
    map: "Crystal Isles",
    img: "crystal_wyvern_queen.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "massive", count: 1 },
          { id: "devious", count: 1 },
          { id: "skylord", count: 1 },
          { id: "immune", count: 1 },
          { id: "brute", count: 1 },
          { id: "crystal_talon", count: 5 },
          { id: "primal_crystal", count: 10 },
        ],
        element: 40,
        unlocks: [
          "테크 토대",
          "테크 건틀릿",
          "테크 해치프레임",
          "테크 복제기",
          "테크 트랩도어",
          "테크 창문",
          "테크 창문틀",
          "경사진 테크 지붕",
          "경사진 테크 벽(좌)",
          "경사진 테크 벽(우)",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "depths", count: 1 },
          { id: "hunter", count: 1 },
          { id: "clever", count: 1 },
          { id: "devourer", count: 1 },
          { id: "strong", count: 1 },
          { id: "cunning", count: 1 },
          { id: "crystal_talon", count: 10 },
          { id: "primal_crystal", count: 20 },
          { id: "alpha_crystal_talon", count: 1 },
        ],
        element: 110,
        unlocks: [
          "테크 전용 보관함",
          "테크 소총",
          "테크 부츠",
          "테크 송신기",
          "테크 포스필드",
          "진공 구획",
          "테크 공룡 게이트",
          "테크 베히모스 게이트",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "pack", count: 1 },
          { id: "shadows", count: 1 },
          { id: "stalker", count: 1 },
          { id: "lost", count: 1 },
          { id: "gatekeeper", count: 1 },
          { id: "crag", count: 1 },
          { id: "destroyer", count: 1 },
          { id: "crystal_talon", count: 15 },
          { id: "primal_crystal", count: 30 },
          { id: "alpha_crystal_talon", count: 3 },
        ],
        element: 220,
        unlocks: [
          "테크 전용 보관함",
          "테크 헬멧",
          "테크 흉갑",
          "테크 텔레포터",
          "테크 렉스 안장",
          "메갈로돈/모사/타페야라 테크 안장",
          "크리스탈 와이번 퀸 트로피",
        ],
      },
    },
  },
  {
    id: "dinopithecus",
    name: "디노피테쿠스 킹",
    map: "Lost Island",
    img: "dinopithecus_king.png",
    difficulties: {
      gamma: {
        level: "Gamma",
        req: [
          { id: "strong", count: 1 },
          { id: "pack", count: 1 },
          { id: "clever", count: 1 },
          { id: "hunter", count: 1 },
        ],
        element: 80,
        unlocks: [
          "테크 복제기",
          "테크 건틀릿",
          "테크 레깅스",
          "테크 먹이통",
          "테크 작물 밭",
          "테크 토대",
          "테크 천장",
          "테크 벽",
          "테크 문",
          "테크 문틀",
          "테크 창문",
          "테크 창문틀",
          "테크 해치프레임",
          "테크 트랩도어",
        ],
      },
      beta: {
        level: "Beta",
        req: [
          { id: "strong", count: 1 },
          { id: "pack", count: 1 },
          { id: "clever", count: 1 },
          { id: "hunter", count: 1 },
          { id: "claw", count: 5 },
          { id: "sarco", count: 5 },
        ],
        element: 220,
        unlocks: [
          "테크 전용 보관함",
          "테크 소총",
          "테크 부츠",
          "테크 송신기",
          "테크 포스필드",
          "테크 발전기",
          "테크 공룡 게이트",
          "테크 공룡 문",
          "진공 구획",
        ],
      },
      alpha: {
        level: "Alpha",
        req: [
          { id: "strong", count: 1 },
          { id: "pack", count: 1 },
          { id: "clever", count: 1 },
          { id: "hunter", count: 1 },
          { id: "claw", count: 10 },
          { id: "sarco", count: 10 },
          { id: "spino_sail", count: 10 },
        ],
        element: 440,
        unlocks: [
          "테크 전용 보관함",
          "테크 헬멧",
          "테크 흉갑",
          "테크 텔레포터",
          "테크 수류탄",
          "클로닝 챔버",
          "테크 렉스 안장",
          "메갈로돈 테크 안장",
          "타페야라 테크 안장",
          "모사사우루스 테크 안장",
          "디노피테쿠스 킹 트로피",
          "디노피테쿠스 킹 깃발",
        ],
      },
    },
  },
  
];

// [3] BP 도감 데이터 (기존 유지)
const bpDatabase = [
  {
    id: "bp_pick",
    name: "금속 곡괭이",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "metal_pick.png",
  },
  {
    id: "bp_hatchet",
    name: "금속 도끼",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "metal_hatchet.png",
  },
  {
    id: "bp_crossbow",
    name: "쇠뇌",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "crossbow.png",
  },
  {
    id: "bp_sword_metal",
    name: "검",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "metal_sword.png",
  },
  {
    id: "bp_whip",
    name: "채찍",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "whip.png",
  },
  {
    id: "bp_shotgun",
    name: "펌프 샷건",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "pump_shotgun.png",
  },
  {
    id: "bp_saw",
    name: "사슬톱",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "saw.png",
  },
  {
    id: "bp_longneck",
    name: "장총",
    folder: "⚔️ 무기 & 도구",
    default: 100,
    unit: "%",
    img: "longneck.png",
  },
  {
    id: "bp_rex_saddle",
    name: "렉스 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "rex_saddle.png",
  },
  {
    id: "bp_giga_saddle",
    name: "기가노토 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "giga_saddle.png",
  },
  {
    id: "bp_theri_saddle",
    name: "테리지노 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "theri_saddle.png",
  },
  {
    id: "bp_yuty_saddle",
    name: "유티라누스 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "yuty_saddle.png",
  },
  {
    id: "Megatherium_Saddle",
    name: "메가테리움 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "Megatherium_Saddle.png",
  },
  {
    id: "bp_argent_saddle",
    name: "아르젠타비스 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "argent_saddle.png",
  },
  {
    id: "bp_tuso_saddle",
    name: "투소테우티스 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "tuso_saddle.png",
  },
  {
    id: "bp_bassi_saddle",
    name: "바실로사우루스 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "basilo_saddle.png",
  },
  {
    id: "bp_ankylo_saddle",
    name: "안킬로 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "ankylo_saddle.png",
  },
  {
    id: "bp_daeodon_saddle",
    name: "다에오돈 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "daeodon_saddle.png",
  },
  {
    id: "bp_mantis_saddle",
    name: "사마귀 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "mantis_saddle.png",
  },
  {
    id: "bp_procoptodon_saddle",
    name: "프로콥토돈 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "procoptodon_saddle.png",
  },
  {
    id: "bp_mana_saddle",
    name: "마나가르마 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "mana_saddle.png",
  },
  {
    id: "bp_owl_saddle",
    name: "눈올빼미 안장",
    folder: "🦕 안장",
    default: 25,
    unit: "",
    img: "owl_saddle.png",
  },
  {
    id: "bp_flak_helmet",
    name: "방탄 헬멧",
    folder: "🛡️ 방탄 갑옷 (Flak)",
    default: 100,
    unit: "",
    img: "flak_helmet.png",
  },
  {
    id: "bp_flak_chest",
    name: "방탄 흉갑",
    folder: "🛡️ 방탄 갑옷 (Flak)",
    default: 100,
    unit: "",
    img: "flak_chest.png",
  },
  {
    id: "bp_flak_gloves",
    name: "방탄 장갑",
    folder: "🛡️ 방탄 갑옷 (Flak)",
    default: 100,
    unit: "",
    img: "flak_gloves.png",
  },
  {
    id: "bp_flak_leggings",
    name: "방탄 레깅스",
    folder: "🛡️ 방탄 갑옷 (Flak)",
    default: 100,
    unit: "",
    img: "flak_leggings.png",
  },
  {
    id: "bp_flak_boots",
    name: "방탄 부츠",
    folder: "🛡️ 방탄 갑옷 (Flak)",
    default: 100,
    unit: "",
    img: "flak_boots.png",
  },
  {
    id: "bp_fur_helmet",
    name: "모피 모자",
    folder: "❄️ 모피 옷 (Fur)",
    default: 40,
    unit: "",
    img: "fur_helmet.png",
  },
  {
    id: "bp_fur_chest",
    name: "모피 흉갑",
    folder: "❄️ 모피 옷 (Fur)",
    default: 40,
    unit: "",
    img: "fur_chest.png",
  },
  {
    id: "bp_fur_gloves",
    name: "모피 장갑",
    folder: "❄️ 모피 옷 (Fur)",
    default: 40,
    unit: "",
    img: "fur_gloves.png",
  },
  {
    id: "bp_fur_leggings",
    name: "모피 레깅스",
    folder: "❄️ 모피 옷 (Fur)",
    default: 40,
    unit: "",
    img: "fur_leggings.png",
  },
  {
    id: "bp_fur_boots",
    name: "모피 부츠",
    folder: "❄️ 모피 옷 (Fur)",
    default: 40,
    unit: "",
    img: "fur_boots.png",
  },
  {
    id: "bp_ghillie_helmet",
    name: "길리 가면",
    folder: "🌿 길리 슈트 (Ghillie)",
    default: 40,
    unit: "",
    img: "ghillie_helmet.png",
  },
  {
    id: "bp_ghillie_chest",
    name: "길리 흉갑",
    folder: "🌿 길리 슈트 (Ghillie)",
    default: 40,
    unit: "",
    img: "ghillie_chest.png",
  },
  {
    id: "bp_ghillie_gloves",
    name: "길리 장갑",
    folder: "🌿 길리 슈트 (Ghillie)",
    default: 40,
    unit: "",
    img: "ghillie_gloves.png",
  },
  {
    id: "bp_ghillie_leggings",
    name: "길리 레깅스",
    folder: "🌿 길리 슈트 (Ghillie)",
    default: 40,
    unit: "",
    img: "ghillie_leggings.png",
  },
  {
    id: "bp_ghillie_boots",
    name: "길리 부츠",
    folder: "🌿 길리 슈트 (Ghillie)",
    default: 40,
    unit: "",
    img: "ghillie_boots.png",
  },
];
